[project]
site_name = "QualCoder"
site_url = "https://qualcoder.org"
site_description = "QualCoder Website"
site_author = "QualCoder Teams"
docs_dir = "docs"
repo_url = "https://github.com/QualCoder-Org/qualcoder-org.github.io"
repo_name = "QualCoder-Org/qualcoder-org.github.io"
edit_uri = "edit/main/docs/"
nav = [
	{"Home" = "index.md"},
	{"Blog" = "https://qualcoder.wordpress.com/"},
	{"Resources" = "ressources.md"},
	{"Videos on QualCoder" = "videos.md"},
	{"Studies using QualCoder" = "using.md"},
	{"About Developers" = "about.md"},
	{"Forum" = "https://github.com/ccbogel/QualCoder/discussions"},
	{"en" = [
		"en/index.md",
		"en/1.-Overview.md",
		"en/2.1.-Installation.md",
		"en/2.2.-Settings.md",
		"en/2.3.-AI-Setup.md",
		"en/2.4.-Working-in-a-Team.md",
		"en/3.1.-Creating-a-New-Project.md",
		"en/3.2.-Files.md",
		"en/3.3.-Cases.md",
		"en/3.4.-Attributes.md",
		"en/4.1.-Coding-Text.md",
		"en/4.2.-AI-Assisted-Coding.md",
		"en/4.3.-Coding-Text-on-PDFs.md",
		"en/4.4.-Coding-Images.md",
		"en/4.5.-Coding-Audio-and-Video.md",
		"en/4.6-Code-Organiser.md",
		"en/5.1.-AI-chat-based-analysis.md",
		"en/5.2.-Journals.md",
		"en/5.3.-Reports.md",
		"en/5.4.-Graph.md",
		"en/6.1.-Imports-and-Exports.md",
		"en/6.2.-AI-Prompt-Library.md",
		"en/7.3.-QualCoder-Development.md",
		"en/7.4.-SQlite-Data-Structure.md",
		"en/7.5.-AI-Technical-Information.md",
		"en/7.6.-How-to-contribute.md"						
	]},
	{"fr" = [
		"fr/index.md",
		"fr/1.-Overview.md",
		"fr/2.1.-Installation.md",
		"fr/2.2.-Settings.md",
		"fr/2.3.-AI-Setup.md",
		"fr/2.4.-Working-in-a-Team.md",
		"fr/3.1.-Creating-a-New-Project.md",
		"fr/3.2.-Files.md",
		"fr/3.3.-Cases.md",
		"fr/3.4.-Attributes.md",
		"fr/4.1.-Coding-Text.md",
		"fr/4.2.-AI-Assisted-Coding.md",
		"fr/4.3.-Coding-Text-on-PDFs.md",
		"fr/4.4.-Coding-Images.md",
		"fr/4.5.-Coding-Audio-and-Video.md",
		"fr/4.6-Code-Organiser.md",
		"fr/5.1.-AI-chat-based-analysis.md",
		"fr/5.2.-Journals.md",
		"fr/5.3.-Reports.md",
		"fr/5.4.-Graph.md",
		"fr/6.1.-Imports-and-Exports.md",
		"fr/6.2.-AI-Prompt-Library.md",
		"fr/7.3.-QualCoder-Development.md",
		"fr/7.4.-SQlite-Data-Structure.md",
		"fr/7.5.-AI-Technical-Information.md",
		"fr/7.6.-How-to-contribute.md"						
	
	]},
	{"es" = [
		"es/index.md",
		"es/1.-Overview.md",
		"es/2.1.-Installation.md",
		"es/2.2.-Settings.md",
		"es/2.3.-AI-Setup.md",
		"es/2.4.-Working-in-a-Team.md",
		"es/3.1.-Creating-a-New-Project.md",
		"es/3.2.-Files.md",
		"es/3.3.-Cases.md",
		"es/3.4.-Attributes.md",
		"es/4.1.-Coding-Text.md",
		"es/4.2.-AI-Assisted-Coding.md",
		"es/4.3.-Coding-Text-on-PDFs.md",
		"es/4.4.-Coding-Images.md",
		"es/4.5.-Coding-Audio-and-Video.md",
		"es/4.6-Code-Organiser.md",
		"es/5.1.-AI-chat-based-analysis.md",
		"es/5.2.-Journals.md",
		"es/5.3.-Reports.md",
		"es/5.4.-Graph.md",
		"es/6.1.-Imports-and-Exports.md",
		"es/6.2.-AI-Prompt-Library.md",
		"es/7.3.-QualCoder-Development.md",
		"es/7.4.-SQlite-Data-Structure.md",
		"es/7.5.-AI-Technical-Information.md",
		"es/7.6.-How-to-contribute.md"						
	
	]},
	{"de" = [
		"de/index.md",
		"de/1.-Overview.md",
		"de/2.1.-Installation.md",
		"de/2.2.-Settings.md",
		"de/2.3.-AI-Setup.md",
		"de/2.4.-Working-in-a-Team.md",
		"de/3.1.-Creating-a-New-Project.md",
		"de/3.2.-Files.md",
		"de/3.3.-Cases.md",
		"de/3.4.-Attributes.md",
		"de/4.1.-Coding-Text.md",
		"de/4.2.-AI-Assisted-Coding.md",
		"de/4.3.-Coding-Text-on-PDFs.md",
		"de/4.4.-Coding-Images.md",
		"de/4.5.-Coding-Audio-and-Video.md",
		"de/4.6-Code-Organiser.md",
		"de/5.1.-AI-chat-based-analysis.md",
		"de/5.2.-Journals.md",
		"de/5.3.-Reports.md",
		"de/5.4.-Graph.md",
		"de/6.1.-Imports-and-Exports.md",
		"de/6.2.-AI-Prompt-Library.md",
		"de/7.3.-QualCoder-Development.md",
		"de/7.4.-SQlite-Data-Structure.md",
		"de/7.5.-AI-Technical-Information.md",
		"de/7.6.-How-to-contribute.md"						
	]}
]

[project.theme]
variant = "modern" # classic = old them vs modern
language = "en"
logo = "images/logo.png"
features = [
  "content.action.edit", # Edit this page
  "content.action.view",  # View source of this page
  "navigation.sections",
  "navigation.expand",
  "navigation.path",
  "navigation.indexes",
  "toc.integrate",
  "search.highlight",
  "navigation.footer"
]

[[project.theme.palette]]
scheme = "deep purple"
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.extra]
alternate = [
    { name = "English", link = "/en/", lang = "en" },
    { name = "Español", link = "/es/", lang = "es" },
    { name = "Deutsch", link = "/de/", lang = "de" },
    { name = "Français", link = "/fr/", lang = "fr" }
]

